version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '13:00'
    pull-request-branch-name:
      separator: '-'
    open-pull-requests-limit: 10
